# SPDX-License-Identifier: GPL-3.0-or-later

timeout: 0
serial: yes
verbose: yes
editor_enabled: no

/Zizium 0.1 "Seed"
    protocol: limine
    path: boot():/Zizium/Boot/zizium.efi
    cmdline: release=Seed root=C:
    module_path: boot():/Zizium/Boot/zizium-root.zifs
    module_string: zifs-root
    resolution: 1024x768x32
